name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t lailaaaaa/aloafy-backend:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'lailaaaaa/aloafy-backend:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Push to Docker Hub
        run: docker push lailaaaaa/aloafy-backend:latest

  deploy-to-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulation setup
        run: echo "Preparing deployment report..."

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 *PROJET ALOAFY — RAPPORT DEVSECOPS*
            
            🔹 *Statut Trivy :* ✅ Image Scannée & Validée
            🔹 *Auteur :* ${{ github.actor }}
            🔹 *Branche :* ${{ github.ref_name }}
            🔹 *Commit :* ${{ github.event.head_commit.message }}
            
            L'image Docker backend a été inspectée avec succès par Trivy ! Les résultats des vulnérabilités High et Critical sont disponibles dans les logs du build.
